name: Integración Continua
on:
 push:
 branches:
 - main
 pull_request:
 branches:
 - main
jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - name: Clonar el repositorio
 uses: actions/checkout@v3
 - name: Configurar Node.js
 uses: actions/setup-node@v3
 with:
 node-version: 16
 - name: Instalar dependencias
 run: npm install
 - name: Ejecutar pruebas
 run: npm test
